version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_template
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: template
    ports:
      - "5432:5432"

volumes:
  postgres_data:
